TOP=../..
include $(TOP)/configure/CONFIG

DB += xybo.db
DB += xybi.db
DB += xy220.substitutions
DB += xy240.substitutions

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
